torso_effort_controller:
  type: effort_controllers/JointPositionController
  joint: torso_joint
  pid: {p: 5000.0, i: 100.0, d: 0.0, i_clamp: 500} #, i_clamp: 10

torso_position_controller:
  type: position_controllers/JointPositionController
  joint: torso_joint

robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

#control pan tilt with simple Float64 msgs
pan_tilt_controller:
    type: position_controllers/JointGroupPositionController
    joints: ['head_pan_joint', 'head_tilt_joint']
    publish_rate: 50

#control pan tilt with trajectory msgs
pan_tilt_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: ['head_pan_joint', 'head_tilt_joint']
  
pan_tilt_posvel_trajectory_controller:
  type: pos_vel_controllers/JointTrajectoryController
  joints: ['head_pan_joint', 'head_tilt_joint']

mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 10.0               # default: 50
  pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.002]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3284
  wheel_radius : 0.075
  # slip_factor: 1.0

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0

  enable_odom_tf: true

  # Base frame_id
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.4  # m/s
      min_velocity           : -0.2 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.15  # m/s^2
      min_acceleration       : -0.15 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # rad/s^2

arm_trajectory_controller:
  type: pos_vel_controllers/JointTrajectoryController
  joints:
     - rotation1_joint
     - shoulder1_joint 
     - shoulder2_joint 
     - rotation2_joint 
     - shoulder3_joint 
     - wrist_joint 
  publish_rate: 50
  constraints:
    goal_time: 2.5                  
    stopped_velocity_tolerance: 0.05 
    rotation1_joint: {trajectory: 1.2, goal: 0.8}
    shoulder1_joint: {trajectory: 1.2, goal: 0.8}
    shoulder2_joint: {trajectory: 1.2, goal: 0.8}
    rotation2_joint: {trajectory: 1.2, goal: 0.8}
    shoulder3_joint: {trajectory: 1.2, goal: 0.8}
    wrist_joint: {trajectory: 1.2, goal: 0.8}


gripper_controller:
 type: pos_vel_controllers/GripperActionController 
 left_finger_joint: 'left_finger_joint'
 right_finger_joint: 'right_finger_joint'
 goal_tolerance: 0.005
 stalled_velocity_threshold: 0.01
 stall_timeout: 1.0
 joints_vel: 1.0
 action_monitor_rate: 50
      
#gazebo_ros_control:
# pid_gains:
#   left_finger_joint: {p: 50.0, i: 0.01, d: 10.0}
#   right_finger_joint: {p: 50.0, i: 0.01, d: 10.0}
#  head_pan_joint: {p: 150.0, i: 0.02, d: 10.0}
#  head_tilt_joint: {p: 150.0, i: 0.02, d: 10.0}

